# Generated by Django 2.2.3 on 2019-07-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=30)),
                ('answer', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Contact Keyword',
                'verbose_name_plural': 'Contact Keywords',
            },
        ),
    ]
